# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddFlavor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddFlavor(object):
    def setupUi(self, AddFlavor):
        AddFlavor.setObjectName("AddFlavor")
        AddFlavor.resize(421, 507)
        AddFlavor.setStyleSheet("QDialog {background-color: white;}")
        self.label_addimagetitle = QtWidgets.QLabel(AddFlavor)
        self.label_addimagetitle.setGeometry(QtCore.QRect(110, 20, 201, 41))
        self.label_addimagetitle.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 25px;\n"
"}")
        self.label_addimagetitle.setObjectName("label_addimagetitle")
        self.label_add_flavorname = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorname.setGeometry(QtCore.QRect(50, 100, 101, 31))
        self.label_add_flavorname.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorname.setObjectName("label_add_flavorname")
        self.lineEdit_add_flavorname = QtWidgets.QLineEdit(AddFlavor)
        self.lineEdit_add_flavorname.setGeometry(QtCore.QRect(170, 100, 201, 31))
        self.lineEdit_add_flavorname.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_flavorname.setText("")
        self.lineEdit_add_flavorname.setObjectName("lineEdit_add_flavorname")
        self.lineEdit_add_flavorid = QtWidgets.QLineEdit(AddFlavor)
        self.lineEdit_add_flavorid.setGeometry(QtCore.QRect(170, 140, 201, 31))
        self.lineEdit_add_flavorid.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_flavorid.setText("")
        self.lineEdit_add_flavorid.setObjectName("lineEdit_add_flavorid")
        self.label_add_flavorid = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorid.setGeometry(QtCore.QRect(50, 140, 101, 31))
        self.label_add_flavorid.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorid.setObjectName("label_add_flavorid")
        self.label_add_flavorvcpu = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorvcpu.setGeometry(QtCore.QRect(50, 180, 101, 31))
        self.label_add_flavorvcpu.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorvcpu.setObjectName("label_add_flavorvcpu")
        self.spinBox_add_flavorvcpu = QtWidgets.QSpinBox(AddFlavor)
        self.spinBox_add_flavorvcpu.setGeometry(QtCore.QRect(170, 180, 171, 31))
        self.spinBox_add_flavorvcpu.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_flavorvcpu.setMaximum(99999)
        self.spinBox_add_flavorvcpu.setObjectName("spinBox_add_flavorvcpu")
        self.label_add_min_disk_dw = QtWidgets.QLabel(AddFlavor)
        self.label_add_min_disk_dw.setGeometry(QtCore.QRect(350, 180, 31, 31))
        self.label_add_min_disk_dw.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk_dw.setObjectName("label_add_min_disk_dw")
        self.spinBox_add_flavorram = QtWidgets.QSpinBox(AddFlavor)
        self.spinBox_add_flavorram.setGeometry(QtCore.QRect(170, 220, 171, 31))
        self.spinBox_add_flavorram.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_flavorram.setMaximum(99999)
        self.spinBox_add_flavorram.setObjectName("spinBox_add_flavorram")
        self.label_add_min_disk_dw_2 = QtWidgets.QLabel(AddFlavor)
        self.label_add_min_disk_dw_2.setGeometry(QtCore.QRect(350, 220, 31, 31))
        self.label_add_min_disk_dw_2.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk_dw_2.setObjectName("label_add_min_disk_dw_2")
        self.label_add_flavorram = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorram.setGeometry(QtCore.QRect(50, 220, 101, 31))
        self.label_add_flavorram.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorram.setObjectName("label_add_flavorram")
        self.spinBox_add_flavordisk = QtWidgets.QSpinBox(AddFlavor)
        self.spinBox_add_flavordisk.setGeometry(QtCore.QRect(170, 260, 171, 31))
        self.spinBox_add_flavordisk.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_flavordisk.setMaximum(99999)
        self.spinBox_add_flavordisk.setObjectName("spinBox_add_flavordisk")
        self.label_add_min_disk_dw_3 = QtWidgets.QLabel(AddFlavor)
        self.label_add_min_disk_dw_3.setGeometry(QtCore.QRect(350, 260, 31, 31))
        self.label_add_min_disk_dw_3.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk_dw_3.setObjectName("label_add_min_disk_dw_3")
        self.label_add_flavordisk = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavordisk.setGeometry(QtCore.QRect(50, 260, 101, 31))
        self.label_add_flavordisk.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavordisk.setObjectName("label_add_flavordisk")
        self.spinBox_add_flavorephemeral = QtWidgets.QSpinBox(AddFlavor)
        self.spinBox_add_flavorephemeral.setGeometry(QtCore.QRect(170, 300, 171, 31))
        self.spinBox_add_flavorephemeral.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_flavorephemeral.setMaximum(99999)
        self.spinBox_add_flavorephemeral.setObjectName("spinBox_add_flavorephemeral")
        self.label_add_min_disk_dw_4 = QtWidgets.QLabel(AddFlavor)
        self.label_add_min_disk_dw_4.setGeometry(QtCore.QRect(350, 300, 31, 31))
        self.label_add_min_disk_dw_4.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk_dw_4.setObjectName("label_add_min_disk_dw_4")
        self.label_add_flavorex = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorex.setGeometry(QtCore.QRect(50, 300, 101, 31))
        self.label_add_flavorex.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorex.setObjectName("label_add_flavorex")
        self.spinBox_add_flavorswap = QtWidgets.QSpinBox(AddFlavor)
        self.spinBox_add_flavorswap.setGeometry(QtCore.QRect(170, 340, 171, 31))
        self.spinBox_add_flavorswap.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_flavorswap.setMaximum(99999)
        self.spinBox_add_flavorswap.setObjectName("spinBox_add_flavorswap")
        self.label_add_min_disk_dw_5 = QtWidgets.QLabel(AddFlavor)
        self.label_add_min_disk_dw_5.setGeometry(QtCore.QRect(350, 340, 31, 31))
        self.label_add_min_disk_dw_5.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk_dw_5.setObjectName("label_add_min_disk_dw_5")
        self.label_add_flavorswap = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorswap.setGeometry(QtCore.QRect(50, 340, 101, 31))
        self.label_add_flavorswap.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorswap.setObjectName("label_add_flavorswap")
        self.spinBox_add_flavorrxtx = QtWidgets.QSpinBox(AddFlavor)
        self.spinBox_add_flavorrxtx.setGeometry(QtCore.QRect(170, 380, 201, 31))
        self.spinBox_add_flavorrxtx.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_flavorrxtx.setMaximum(99999)
        self.spinBox_add_flavorrxtx.setProperty("value", 1)
        self.spinBox_add_flavorrxtx.setObjectName("spinBox_add_flavorrxtx")
        self.label_add_flavorrxtx = QtWidgets.QLabel(AddFlavor)
        self.label_add_flavorrxtx.setGeometry(QtCore.QRect(50, 380, 111, 31))
        self.label_add_flavorrxtx.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_flavorrxtx.setObjectName("label_add_flavorrxtx")
        self.pushButton_add_addflavor = QtWidgets.QPushButton(AddFlavor)
        self.pushButton_add_addflavor.setGeometry(QtCore.QRect(150, 440, 121, 41))
        self.pushButton_add_addflavor.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_addflavor.setObjectName("pushButton_add_addflavor")

        self.retranslateUi(AddFlavor)
        QtCore.QMetaObject.connectSlotsByName(AddFlavor)

    def retranslateUi(self, AddFlavor):
        _translate = QtCore.QCoreApplication.translate
        AddFlavor.setWindowTitle(_translate("AddFlavor", "Dialog"))
        self.label_addimagetitle.setText(_translate("AddFlavor", "<html><head/><body><p align=\"center\">创建云主机类型</p></body></html>"))
        self.label_add_flavorname.setText(_translate("AddFlavor", "类型名称:"))
        self.label_add_flavorid.setText(_translate("AddFlavor", "类型ID："))
        self.label_add_flavorvcpu.setText(_translate("AddFlavor", "VCPU数量："))
        self.label_add_min_disk_dw.setText(_translate("AddFlavor", "个"))
        self.label_add_min_disk_dw_2.setText(_translate("AddFlavor", "MB"))
        self.label_add_flavorram.setText(_translate("AddFlavor", "内存："))
        self.label_add_min_disk_dw_3.setText(_translate("AddFlavor", "GB"))
        self.label_add_flavordisk.setText(_translate("AddFlavor", "根磁盘："))
        self.label_add_min_disk_dw_4.setText(_translate("AddFlavor", "GB"))
        self.label_add_flavorex.setText(_translate("AddFlavor", "临时磁盘："))
        self.label_add_min_disk_dw_5.setText(_translate("AddFlavor", "MB"))
        self.label_add_flavorswap.setText(_translate("AddFlavor", "Swap磁盘："))
        self.label_add_flavorrxtx.setText(_translate("AddFlavor", "RX/TX因子："))
        self.pushButton_add_addflavor.setText(_translate("AddFlavor", "创建"))
