# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddNetwork.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNetwork(object):
    def setupUi(self, AddNetwork):
        AddNetwork.setObjectName("AddNetwork")
        AddNetwork.resize(427, 532)
        AddNetwork.setMinimumSize(QtCore.QSize(427, 532))
        AddNetwork.setMaximumSize(QtCore.QSize(427, 502))
        AddNetwork.setStyleSheet("QDialog {background-color: white;}")
        self.label_add_networkname = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkname.setGeometry(QtCore.QRect(60, 80, 81, 31))
        self.label_add_networkname.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkname.setObjectName("label_add_networkname")
        self.label_add_networkadmin = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkadmin.setGeometry(QtCore.QRect(60, 280, 111, 31))
        self.label_add_networkadmin.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkadmin.setObjectName("label_add_networkadmin")
        self.lineEdit_add_networkname = QtWidgets.QLineEdit(AddNetwork)
        self.lineEdit_add_networkname.setGeometry(QtCore.QRect(170, 80, 201, 31))
        self.lineEdit_add_networkname.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_networkname.setObjectName("lineEdit_add_networkname")
        self.comboBox_add_networkproject = QtWidgets.QComboBox(AddNetwork)
        self.comboBox_add_networkproject.setGeometry(QtCore.QRect(170, 120, 201, 31))
        self.comboBox_add_networkproject.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"                        ")
        self.comboBox_add_networkproject.setObjectName("comboBox_add_networkproject")
        self.checkBox_add_networkadmin = QtWidgets.QCheckBox(AddNetwork)
        self.checkBox_add_networkadmin.setGeometry(QtCore.QRect(180, 280, 91, 31))
        self.checkBox_add_networkadmin.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_networkadmin.setObjectName("checkBox_add_networkadmin")
        self.label_add_networkproject = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkproject.setGeometry(QtCore.QRect(60, 120, 81, 31))
        self.label_add_networkproject.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkproject.setObjectName("label_add_networkproject")
        self.comboBox_add_networktype = QtWidgets.QComboBox(AddNetwork)
        self.comboBox_add_networktype.setGeometry(QtCore.QRect(170, 160, 201, 31))
        self.comboBox_add_networktype.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"                        ")
        self.comboBox_add_networktype.setObjectName("comboBox_add_networktype")
        self.label_add_networktype = QtWidgets.QLabel(AddNetwork)
        self.label_add_networktype.setGeometry(QtCore.QRect(60, 160, 91, 31))
        self.label_add_networktype.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networktype.setObjectName("label_add_networktype")
        self.label_add_networktitle = QtWidgets.QLabel(AddNetwork)
        self.label_add_networktitle.setGeometry(QtCore.QRect(150, 20, 131, 41))
        self.label_add_networktitle.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 25px;\n"
"}")
        self.label_add_networktitle.setObjectName("label_add_networktitle")
        self.label_add_networkshared = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkshared.setGeometry(QtCore.QRect(60, 320, 111, 31))
        self.label_add_networkshared.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkshared.setObjectName("label_add_networkshared")
        self.label_add_networkout = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkout.setGeometry(QtCore.QRect(60, 360, 111, 31))
        self.label_add_networkout.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkout.setObjectName("label_add_networkout")
        self.label_add_networkifsubnet = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkifsubnet.setGeometry(QtCore.QRect(60, 400, 111, 31))
        self.label_add_networkifsubnet.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkifsubnet.setObjectName("label_add_networkifsubnet")
        self.checkBox_add_networkshared = QtWidgets.QCheckBox(AddNetwork)
        self.checkBox_add_networkshared.setGeometry(QtCore.QRect(180, 320, 91, 31))
        self.checkBox_add_networkshared.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_networkshared.setObjectName("checkBox_add_networkshared")
        self.checkBox_add_networkout = QtWidgets.QCheckBox(AddNetwork)
        self.checkBox_add_networkout.setGeometry(QtCore.QRect(180, 360, 91, 31))
        self.checkBox_add_networkout.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_networkout.setObjectName("checkBox_add_networkout")
        self.checkBox_add_networkifsubnet = QtWidgets.QCheckBox(AddNetwork)
        self.checkBox_add_networkifsubnet.setGeometry(QtCore.QRect(180, 400, 91, 31))
        self.checkBox_add_networkifsubnet.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_networkifsubnet.setObjectName("checkBox_add_networkifsubnet")
        self.label_add_networkzone = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkzone.setGeometry(QtCore.QRect(60, 200, 91, 31))
        self.label_add_networkzone.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkzone.setObjectName("label_add_networkzone")
        self.comboBox_add_networkzone = QtWidgets.QComboBox(AddNetwork)
        self.comboBox_add_networkzone.setGeometry(QtCore.QRect(170, 200, 201, 31))
        self.comboBox_add_networkzone.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"                        ")
        self.comboBox_add_networkzone.setObjectName("comboBox_add_networkzone")
        self.pushButton_add_addnetwork = QtWidgets.QPushButton(AddNetwork)
        self.pushButton_add_addnetwork.setGeometry(QtCore.QRect(60, 460, 121, 41))
        self.pushButton_add_addnetwork.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_addnetwork.setObjectName("pushButton_add_addnetwork")
        self.pushButton_add_cancelnetwork = QtWidgets.QPushButton(AddNetwork)
        self.pushButton_add_cancelnetwork.setGeometry(QtCore.QRect(250, 460, 121, 41))
        self.pushButton_add_cancelnetwork.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_cancelnetwork.setObjectName("pushButton_add_cancelnetwork")
        self.label_add_networkdesc = QtWidgets.QLabel(AddNetwork)
        self.label_add_networkdesc.setGeometry(QtCore.QRect(60, 240, 91, 31))
        self.label_add_networkdesc.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkdesc.setObjectName("label_add_networkdesc")
        self.lineEdit_add_networkdesc = QtWidgets.QLineEdit(AddNetwork)
        self.lineEdit_add_networkdesc.setGeometry(QtCore.QRect(170, 240, 201, 31))
        self.lineEdit_add_networkdesc.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_networkdesc.setObjectName("lineEdit_add_networkdesc")

        self.retranslateUi(AddNetwork)
        QtCore.QMetaObject.connectSlotsByName(AddNetwork)

    def retranslateUi(self, AddNetwork):
        _translate = QtCore.QCoreApplication.translate
        AddNetwork.setWindowTitle(_translate("AddNetwork", "Dialog"))
        self.label_add_networkname.setText(_translate("AddNetwork", "网络名称:"))
        self.label_add_networkadmin.setText(_translate("AddNetwork", "管理员状态:"))
        self.checkBox_add_networkadmin.setText(_translate("AddNetwork", "启用"))
        self.label_add_networkproject.setText(_translate("AddNetwork", "项目:"))
        self.label_add_networktype.setText(_translate("AddNetwork", "网络类型:"))
        self.label_add_networktitle.setText(_translate("AddNetwork", "<html><head/><body><p align=\"center\">创建网络</p></body></html>"))
        self.label_add_networkshared.setText(_translate("AddNetwork", "共享的:"))
        self.label_add_networkout.setText(_translate("AddNetwork", "外部网络:"))
        self.label_add_networkifsubnet.setText(_translate("AddNetwork", "创建子网:"))
        self.checkBox_add_networkshared.setText(_translate("AddNetwork", "共享"))
        self.checkBox_add_networkout.setText(_translate("AddNetwork", "外部"))
        self.checkBox_add_networkifsubnet.setText(_translate("AddNetwork", "创建"))
        self.label_add_networkzone.setText(_translate("AddNetwork", "可用域:"))
        self.pushButton_add_addnetwork.setText(_translate("AddNetwork", "添加"))
        self.pushButton_add_cancelnetwork.setText(_translate("AddNetwork", "取消"))
        self.label_add_networkdesc.setText(_translate("AddNetwork", "描述:"))
