# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Index.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index(object):
    def setupUi(self, Index):
        Index.setObjectName("Index")
        Index.resize(1120, 740)
        Index.setMinimumSize(QtCore.QSize(1120, 740))
        Index.setMaximumSize(QtCore.QSize(1120, 740))
        self.widget = QtWidgets.QWidget(Index)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1121, 61))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.label_logo = QtWidgets.QLabel(self.widget)
        self.label_logo.setGeometry(QtCore.QRect(0, 0, 241, 61))
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.label_link = QtWidgets.QLabel(self.widget)
        self.label_link.setGeometry(QtCore.QRect(900, 0, 201, 61))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_link.setFont(font)
        self.label_link.setStyleSheet("QLabel {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 15px;\n"
"    color: #333;\n"
"    text-align: left;\n"
"    background-color: transparent;\n"
"}")
        self.label_link.setText("")
        self.label_link.setObjectName("label_link")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(250, 0, 621, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    \n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 40px;\n"
"    color: #C32E24;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(Index)
        self.widget_2.setGeometry(QtCore.QRect(0, 60, 161, 681))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_image = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_image.setGeometry(QtCore.QRect(0, 150, 161, 51))
        self.pushButton_image.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-left: 10px solid white;\n"
"    background-color: #C32E24;\n"
"    color: white\n"
"}")
        self.pushButton_image.setObjectName("pushButton_image")
        self.pushButton_server = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_server.setGeometry(QtCore.QRect(0, 200, 161, 51))
        self.pushButton_server.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-left: 10px solid white;\n"
"    background-color: #C32E24;\n"
"    color: white\n"
"}")
        self.pushButton_server.setObjectName("pushButton_server")
        self.pushButton_network = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_network.setGeometry(QtCore.QRect(0, 100, 161, 51))
        self.pushButton_network.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-left: 10px solid white;\n"
"    background-color: #C32E24;\n"
"    color: white\n"
"}")
        self.pushButton_network.setObjectName("pushButton_network")
        self.pushButton_user = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_user.setGeometry(QtCore.QRect(0, 50, 161, 51))
        self.pushButton_user.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-left: 10px solid white;\n"
"    background-color: #C32E24;\n"
"    color: white\n"
"}")
        self.pushButton_user.setObjectName("pushButton_user")
        self.pushButton_flavor = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_flavor.setGeometry(QtCore.QRect(0, 250, 161, 51))
        self.pushButton_flavor.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-left: 10px solid white;\n"
"    background-color: #C32E24;\n"
"    color: white\n"
"}")
        self.pushButton_flavor.setObjectName("pushButton_flavor")
        self.pushButton_api = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_api.setGeometry(QtCore.QRect(0, 0, 161, 51))
        self.pushButton_api.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-left: 10px solid white;\n"
"    background-color: #C32E24;\n"
"    color: white\n"
"}")
        self.pushButton_api.setObjectName("pushButton_api")
        self.widget_3 = QtWidgets.QWidget(Index)
        self.widget_3.setGeometry(QtCore.QRect(160, 60, 961, 681))
        self.widget_3.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 961, 681))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stack_api = QtWidgets.QWidget()
        self.stack_api.setObjectName("stack_api")
        self.tableWidget = QtWidgets.QTableWidget(self.stack_api)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 951, 671))
        self.tableWidget.setStyleSheet("QTableWidget {border: none;font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section {font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section::hover{background-color: #C32E24; color:white;border: none;}\n"
"QTableWidget::item\n"
"{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    height:35px;\n"
"    font-size:20px;\n"
"}\n"
" \n"
"QTableWidget::item::hover\n"
"{\n"
"    background-color: #C32E24;\n"
"color:white\n"
"}\n"
" \n"
"QTableWidget::item:selected\n"
"{\n"
"    background: #C32E24;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background:transparent;\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border-left:1px solid transparent;;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::sub-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    background:transparent;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    border-top:1px solid transparent;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        self.stackedWidget.addWidget(self.stack_api)
        self.stack_user = QtWidgets.QWidget()
        self.stack_user.setObjectName("stack_user")
        self.label_user = QtWidgets.QLabel(self.stack_user)
        self.label_user.setGeometry(QtCore.QRect(0, 10, 141, 61))
        self.label_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_user.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.label_user.setObjectName("label_user")
        self.tree_users = QtWidgets.QTreeWidget(self.stack_user)
        self.tree_users.setGeometry(QtCore.QRect(0, 80, 951, 601))
        self.tree_users.setStyleSheet("QTreeWidget {border: none;font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section {font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QTreeWidget::item\n"
"{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    height:35px;\n"
"    font-size:20px;\n"
"}\n"
" \n"
"QTreeWidget::item::hover\n"
"{\n"
"    background-color: #C32E24;\n"
"color:white\n"
"}\n"
" \n"
"QTreeWidget::item:selected\n"
"{\n"
"    background: #C32E24;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background:transparent;\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border-left:1px solid transparent;;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::sub-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    background:transparent;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    border-top:1px solid transparent;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}")
        self.tree_users.setObjectName("tree_users")
        font = QtGui.QFont()
        font.setKerning(True)
        self.tree_users.headerItem().setFont(1, font)
        self.pushButton_adduser = QtWidgets.QPushButton(self.stack_user)
        self.pushButton_adduser.setGeometry(QtCore.QRect(800, 20, 131, 41))
        self.pushButton_adduser.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_adduser.setObjectName("pushButton_adduser")
        self.pushButton_deluser = QtWidgets.QPushButton(self.stack_user)
        self.pushButton_deluser.setGeometry(QtCore.QRect(650, 20, 131, 41))
        self.pushButton_deluser.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #fc624e;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #fc624e;\n"
"}")
        self.pushButton_deluser.setObjectName("pushButton_deluser")
        self.stackedWidget.addWidget(self.stack_user)
        self.stack_network = QtWidgets.QWidget()
        self.stack_network.setObjectName("stack_network")
        self.label_network = QtWidgets.QLabel(self.stack_network)
        self.label_network.setGeometry(QtCore.QRect(10, 10, 141, 61))
        self.label_network.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_network.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.label_network.setObjectName("label_network")
        self.tree_networks = QtWidgets.QTreeWidget(self.stack_network)
        self.tree_networks.setGeometry(QtCore.QRect(10, 80, 951, 601))
        self.tree_networks.setStyleSheet("QTreeWidget {border: none;font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section {font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QTreeWidget::item\n"
"{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    height:35px;\n"
"    font-size:20px;\n"
"}\n"
" \n"
"QTreeWidget::item::hover\n"
"{\n"
"    background-color: #C32E24;\n"
"color:white\n"
"}\n"
" \n"
"QTreeWidget::item:selected\n"
"{\n"
"    background: #C32E24;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background:transparent;\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border-left:1px solid transparent;;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::sub-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    background:transparent;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    border-top:1px solid transparent;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}")
        self.tree_networks.setObjectName("tree_networks")
        self.pushButton_addnetwork = QtWidgets.QPushButton(self.stack_network)
        self.pushButton_addnetwork.setGeometry(QtCore.QRect(810, 20, 131, 41))
        self.pushButton_addnetwork.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_addnetwork.setObjectName("pushButton_addnetwork")
        self.pushButton_delnetwork = QtWidgets.QPushButton(self.stack_network)
        self.pushButton_delnetwork.setGeometry(QtCore.QRect(660, 20, 131, 41))
        self.pushButton_delnetwork.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #fc624e;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #fc624e;\n"
"}")
        self.pushButton_delnetwork.setObjectName("pushButton_delnetwork")
        self.pushButton_addsubnet = QtWidgets.QPushButton(self.stack_network)
        self.pushButton_addsubnet.setGeometry(QtCore.QRect(510, 20, 131, 41))
        self.pushButton_addsubnet.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffc8aa;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #ffc8aa;\n"
"}")
        self.pushButton_addsubnet.setObjectName("pushButton_addsubnet")
        self.stackedWidget.addWidget(self.stack_network)
        self.stack_image = QtWidgets.QWidget()
        self.stack_image.setObjectName("stack_image")
        self.pushButton_delimage = QtWidgets.QPushButton(self.stack_image)
        self.pushButton_delimage.setGeometry(QtCore.QRect(660, 20, 131, 41))
        self.pushButton_delimage.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #fc624e;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #fc624e;\n"
"}")
        self.pushButton_delimage.setObjectName("pushButton_delimage")
        self.tree_images = QtWidgets.QTreeWidget(self.stack_image)
        self.tree_images.setGeometry(QtCore.QRect(10, 80, 951, 601))
        self.tree_images.setStyleSheet("QTreeWidget {border: none;font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section {font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QTreeWidget::item\n"
"{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    height:35px;\n"
"    font-size:20px;\n"
"}\n"
" \n"
"QTreeWidget::item::hover\n"
"{\n"
"    background-color: #C32E24;\n"
"color:white\n"
"}\n"
" \n"
"QTreeWidget::item:selected\n"
"{\n"
"    background: #C32E24;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background:transparent;\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border-left:1px solid transparent;;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::sub-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    background:transparent;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    border-top:1px solid transparent;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}")
        self.tree_images.setObjectName("tree_images")
        self.pushButton_addimage = QtWidgets.QPushButton(self.stack_image)
        self.pushButton_addimage.setGeometry(QtCore.QRect(810, 20, 131, 41))
        self.pushButton_addimage.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_addimage.setObjectName("pushButton_addimage")
        self.label_images = QtWidgets.QLabel(self.stack_image)
        self.label_images.setGeometry(QtCore.QRect(10, 10, 141, 61))
        self.label_images.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_images.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.label_images.setObjectName("label_images")
        self.stackedWidget.addWidget(self.stack_image)
        self.stack_server = QtWidgets.QWidget()
        self.stack_server.setObjectName("stack_server")
        self.label_servers = QtWidgets.QLabel(self.stack_server)
        self.label_servers.setGeometry(QtCore.QRect(10, 10, 146, 61))
        self.label_servers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_servers.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.label_servers.setObjectName("label_servers")
        self.pushButton_addservers = QtWidgets.QPushButton(self.stack_server)
        self.pushButton_addservers.setGeometry(QtCore.QRect(810, 20, 131, 41))
        self.pushButton_addservers.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_addservers.setObjectName("pushButton_addservers")
        self.pushButton_delservers = QtWidgets.QPushButton(self.stack_server)
        self.pushButton_delservers.setGeometry(QtCore.QRect(660, 20, 131, 41))
        self.pushButton_delservers.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #fc624e;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #fc624e;\n"
"}")
        self.pushButton_delservers.setObjectName("pushButton_delservers")
        self.tree_servers = QtWidgets.QTreeWidget(self.stack_server)
        self.tree_servers.setGeometry(QtCore.QRect(10, 80, 951, 601))
        self.tree_servers.setStyleSheet("QTreeWidget {border: none;font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section {font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QTreeWidget::item\n"
"{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    height:35px;\n"
"    font-size:20px;\n"
"}\n"
" \n"
"QTreeWidget::item::hover\n"
"{\n"
"    background-color: #C32E24;\n"
"color:white\n"
"}\n"
" \n"
"QTreeWidget::item:selected\n"
"{\n"
"    background: #C32E24;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background:transparent;\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border-left:1px solid transparent;;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::sub-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    background:transparent;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    border-top:1px solid transparent;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}")
        self.tree_servers.setObjectName("tree_servers")
        self.pushButton_refresh = QtWidgets.QPushButton(self.stack_server)
        self.pushButton_refresh.setGeometry(QtCore.QRect(510, 20, 131, 41))
        self.pushButton_refresh.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffc8aa;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #ffc8aa;\n"
"}")
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.stackedWidget.addWidget(self.stack_server)
        self.stack_flavor = QtWidgets.QWidget()
        self.stack_flavor.setObjectName("stack_flavor")
        self.pushButton_delflavors = QtWidgets.QPushButton(self.stack_flavor)
        self.pushButton_delflavors.setGeometry(QtCore.QRect(660, 20, 131, 41))
        self.pushButton_delflavors.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #fc624e;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #fc624e;\n"
"}")
        self.pushButton_delflavors.setObjectName("pushButton_delflavors")
        self.label_flavors = QtWidgets.QLabel(self.stack_flavor)
        self.label_flavors.setGeometry(QtCore.QRect(10, 10, 141, 61))
        self.label_flavors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flavors.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.label_flavors.setObjectName("label_flavors")
        self.tree_flavors = QtWidgets.QTreeWidget(self.stack_flavor)
        self.tree_flavors.setGeometry(QtCore.QRect(10, 80, 951, 601))
        self.tree_flavors.setStyleSheet("QTreeWidget {border: none;font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QHeaderView::section {font: 57 9pt \"HarmonyOS Sans SC\";}\n"
"QTreeWidget::item\n"
"{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    height:35px;\n"
"    font-size:20px;\n"
"}\n"
" \n"
"QTreeWidget::item::hover\n"
"{\n"
"    background-color: #C32E24;\n"
"color:white\n"
"}\n"
" \n"
"QTreeWidget::item:selected\n"
"{\n"
"    background: #C32E24;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background:transparent;\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    border-left:1px solid transparent;;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::sub-page\n"
"{\n"
"    background:transparent;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    background:transparent;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    border-top:1px solid transparent;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:6px;\n"
"    min-height:60px;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background:#C32E24;\n"
"    border-radius:4px;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}\n"
" \n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background:url(none) center no-repeat;\n"
"}")
        self.tree_flavors.setObjectName("tree_flavors")
        self.pushButton_addflavors = QtWidgets.QPushButton(self.stack_flavor)
        self.pushButton_addflavors.setGeometry(QtCore.QRect(810, 20, 131, 41))
        self.pushButton_addflavors.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_addflavors.setObjectName("pushButton_addflavors")
        self.stackedWidget.addWidget(self.stack_flavor)

        self.retranslateUi(Index)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Index)

    def retranslateUi(self, Index):
        _translate = QtCore.QCoreApplication.translate
        Index.setWindowTitle(_translate("Index", "Form"))
        self.label_2.setText(_translate("Index", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">OpenStack</span></p></body></html>"))
        self.pushButton_image.setText(_translate("Index", "镜像"))
        self.pushButton_server.setText(_translate("Index", "云主机"))
        self.pushButton_network.setText(_translate("Index", "网络"))
        self.pushButton_user.setText(_translate("Index", "用户"))
        self.pushButton_flavor.setText(_translate("Index", "云主机类型"))
        self.pushButton_api.setText(_translate("Index", "API"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Index", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Index", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Index", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Index", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Index", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Index", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Index", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Index", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Index", "9"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Index", "组件"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Index", "端点"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Index", "用户认证"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Index", "http://controller:5000/v3/auth/tokens"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Index", "用户端点"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Index", "http://controller:5000/v3/users"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Index", "网络端点"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Index", "http://controller:9696/v2.0/networks"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Index", "子网端点"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Index", "http://controller:9696/v2.0/subnets"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Index", "域端点"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Index", "http://controller:5000/v3/domains"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Index", "项目端点"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Index", "http://controller:5000/v3/projects"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Index", "镜像端点"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Index", "http://controller:9292/v2/images"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Index", "云主机类型端点"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Index", "http://controller:8774/v2/flavors"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Index", "云主机端点"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Index", "http://controller:8774/v2/servers"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_user.setText(_translate("Index", "<html><head/><body><p align=\"center\">用户列表</p></body></html>"))
        self.tree_users.headerItem().setText(0, _translate("Index", "序号"))
        self.tree_users.headerItem().setText(1, _translate("Index", "用户名"))
        self.tree_users.headerItem().setText(2, _translate("Index", "ID"))
        self.tree_users.headerItem().setText(3, _translate("Index", "链接"))
        self.tree_users.headerItem().setText(4, _translate("Index", "域名"))
        self.tree_users.headerItem().setText(5, _translate("Index", "域ID"))
        self.tree_users.headerItem().setText(6, _translate("Index", "项目名"))
        self.tree_users.headerItem().setText(7, _translate("Index", "项目ID"))
        self.pushButton_adduser.setText(_translate("Index", "添加用户"))
        self.pushButton_deluser.setText(_translate("Index", "删除用户"))
        self.label_network.setText(_translate("Index", "<html><head/><body><p align=\"center\">网络列表</p></body></html>"))
        self.tree_networks.headerItem().setText(0, _translate("Index", "序号"))
        self.tree_networks.headerItem().setText(1, _translate("Index", "网络名称"))
        self.tree_networks.headerItem().setText(2, _translate("Index", "网络ID"))
        self.tree_networks.headerItem().setText(3, _translate("Index", "项目ID"))
        self.tree_networks.headerItem().setText(4, _translate("Index", "供应商网络类型"))
        self.tree_networks.headerItem().setText(5, _translate("Index", "是否共享"))
        self.tree_networks.headerItem().setText(6, _translate("Index", "状态"))
        self.tree_networks.headerItem().setText(7, _translate("Index", "创建于"))
        self.pushButton_addnetwork.setText(_translate("Index", "添加网络"))
        self.pushButton_delnetwork.setText(_translate("Index", "删除网络"))
        self.pushButton_addsubnet.setText(_translate("Index", "添加子网"))
        self.pushButton_delimage.setText(_translate("Index", "删除镜像"))
        self.tree_images.headerItem().setText(0, _translate("Index", "序号"))
        self.tree_images.headerItem().setText(1, _translate("Index", "镜像名称"))
        self.tree_images.headerItem().setText(2, _translate("Index", "镜像ID"))
        self.tree_images.headerItem().setText(3, _translate("Index", "镜像大小"))
        self.tree_images.headerItem().setText(4, _translate("Index", "容器格式"))
        self.tree_images.headerItem().setText(5, _translate("Index", "磁盘格式"))
        self.tree_images.headerItem().setText(6, _translate("Index", "状态"))
        self.tree_images.headerItem().setText(7, _translate("Index", "创建时间"))
        self.pushButton_addimage.setText(_translate("Index", "创建镜像"))
        self.label_images.setText(_translate("Index", "镜像列表"))
        self.label_servers.setText(_translate("Index", "云主机列表"))
        self.pushButton_addservers.setText(_translate("Index", "创建云主机"))
        self.pushButton_delservers.setText(_translate("Index", "删除云主机"))
        self.tree_servers.headerItem().setText(0, _translate("Index", "序号"))
        self.tree_servers.headerItem().setText(1, _translate("Index", "云主机名称"))
        self.tree_servers.headerItem().setText(2, _translate("Index", "云主机ID"))
        self.tree_servers.headerItem().setText(3, _translate("Index", "IP地址"))
        self.tree_servers.headerItem().setText(4, _translate("Index", "云主机类型"))
        self.tree_servers.headerItem().setText(5, _translate("Index", "状态"))
        self.tree_servers.headerItem().setText(6, _translate("Index", "可用域"))
        self.tree_servers.headerItem().setText(7, _translate("Index", "密钥对"))
        self.tree_servers.headerItem().setText(8, _translate("Index", "创建时间"))
        self.pushButton_refresh.setText(_translate("Index", "刷新"))
        self.pushButton_delflavors.setText(_translate("Index", "删除云主机类型"))
        self.label_flavors.setText(_translate("Index", "云主机类型列表"))
        self.tree_flavors.headerItem().setText(0, _translate("Index", "序号"))
        self.tree_flavors.headerItem().setText(1, _translate("Index", "云主机类型名称"))
        self.tree_flavors.headerItem().setText(2, _translate("Index", "云主机类型ID"))
        self.tree_flavors.headerItem().setText(3, _translate("Index", "CPU数量"))
        self.tree_flavors.headerItem().setText(4, _translate("Index", "内存大小"))
        self.tree_flavors.headerItem().setText(5, _translate("Index", "磁盘大小"))
        self.tree_flavors.headerItem().setText(6, _translate("Index", "临时存储大小"))
        self.tree_flavors.headerItem().setText(7, _translate("Index", "Swap磁盘"))
        self.tree_flavors.headerItem().setText(8, _translate("Index", "RX/TX因子"))
        self.pushButton_addflavors.setText(_translate("Index", "创建云主机类型"))
