# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 740)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_OpenStack = QtWidgets.QAction(MainWindow)
        self.action_OpenStack.setObjectName("action_OpenStack")
        self.action_OpenStackDocs = QtWidgets.QAction(MainWindow)
        self.action_OpenStackDocs.setObjectName("action_OpenStackDocs")
        self.action_CSDN = QtWidgets.QAction(MainWindow)
        self.action_CSDN.setObjectName("action_CSDN")
        self.menu.addAction(self.action_OpenStack)
        self.menu.addAction(self.action_OpenStackDocs)
        self.menu_2.addAction(self.action_CSDN)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menu_2.setTitle(_translate("MainWindow", "作者"))
        self.action_OpenStack.setText(_translate("MainWindow", "OpenStack"))
        self.action_OpenStackDocs.setText(_translate("MainWindow", "OpenStackDocs"))
        self.action_CSDN.setText(_translate("MainWindow", "CSDN"))
