# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\NetworkTypeVlan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetworkTypeVlan(object):
    def setupUi(self, NetworkTypeVlan):
        NetworkTypeVlan.setObjectName("NetworkTypeVlan")
        NetworkTypeVlan.resize(400, 239)
        NetworkTypeVlan.setMinimumSize(QtCore.QSize(400, 239))
        NetworkTypeVlan.setMaximumSize(QtCore.QSize(400, 239))
        NetworkTypeVlan.setStyleSheet("QDialog {background-color: white;}")
        self.pushButton_add_addunetworktype = QtWidgets.QPushButton(NetworkTypeVlan)
        self.pushButton_add_addunetworktype.setGeometry(QtCore.QRect(150, 160, 121, 41))
        self.pushButton_add_addunetworktype.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_addunetworktype.setObjectName("pushButton_add_addunetworktype")
        self.label_addnetworktypetitle = QtWidgets.QLabel(NetworkTypeVlan)
        self.label_addnetworktypetitle.setGeometry(QtCore.QRect(130, 10, 161, 41))
        self.label_addnetworktypetitle.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 25px;\n"
"}")
        self.label_addnetworktypetitle.setObjectName("label_addnetworktypetitle")
        self.lineEdit_add_networktype = QtWidgets.QLineEdit(NetworkTypeVlan)
        self.lineEdit_add_networktype.setGeometry(QtCore.QRect(160, 70, 201, 31))
        self.lineEdit_add_networktype.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_networktype.setObjectName("lineEdit_add_networktype")
        self.label_add_networktype = QtWidgets.QLabel(NetworkTypeVlan)
        self.label_add_networktype.setGeometry(QtCore.QRect(50, 70, 101, 31))
        self.label_add_networktype.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networktype.setObjectName("label_add_networktype")
        self.lineEdit_add_networkvlanid = QtWidgets.QLineEdit(NetworkTypeVlan)
        self.lineEdit_add_networkvlanid.setGeometry(QtCore.QRect(160, 110, 201, 31))
        self.lineEdit_add_networkvlanid.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_networkvlanid.setObjectName("lineEdit_add_networkvlanid")
        self.label_add_networkvlanid = QtWidgets.QLabel(NetworkTypeVlan)
        self.label_add_networkvlanid.setGeometry(QtCore.QRect(50, 110, 101, 31))
        self.label_add_networkvlanid.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_networkvlanid.setObjectName("label_add_networkvlanid")

        self.retranslateUi(NetworkTypeVlan)
        QtCore.QMetaObject.connectSlotsByName(NetworkTypeVlan)

    def retranslateUi(self, NetworkTypeVlan):
        _translate = QtCore.QCoreApplication.translate
        NetworkTypeVlan.setWindowTitle(_translate("NetworkTypeVlan", "Dialog"))
        self.pushButton_add_addunetworktype.setText(_translate("NetworkTypeVlan", "选择"))
        self.label_addnetworktypetitle.setText(_translate("NetworkTypeVlan", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_add_networktype.setText(_translate("NetworkTypeVlan", "物理网络:"))
        self.label_add_networkvlanid.setText(_translate("NetworkTypeVlan", "段ID:"))
