from .AddUser import Ui_AddUser
from .Index import Ui_Index
from .Login import Ui_Login
from .MainWindow import Ui_MainWindow
from .AddNetwork import Ui_AddNetwork
from .NetworkType import Ui_NetworkType
from .AddSubnet import Ui_AddSubnet
from .NetworkTypeVlan import Ui_NetworkTypeVlan
from .AddImage import Ui_AddImage
from .AddFlavor import Ui_AddFlavor
from .AddServer import Ui_AddServer
