# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddImage(object):
    def setupUi(self, AddImage):
        AddImage.setObjectName("AddImage")
        AddImage.resize(423, 547)
        AddImage.setStyleSheet("QDialog {background-color: white;}")
        self.label_add_imagename = QtWidgets.QLabel(AddImage)
        self.label_add_imagename.setGeometry(QtCore.QRect(60, 100, 101, 31))
        self.label_add_imagename.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_imagename.setObjectName("label_add_imagename")
        self.label_addimagetitle = QtWidgets.QLabel(AddImage)
        self.label_addimagetitle.setGeometry(QtCore.QRect(130, 20, 161, 41))
        self.label_addimagetitle.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 25px;\n"
"}")
        self.label_addimagetitle.setObjectName("label_addimagetitle")
        self.lineEdit_add_imagename = QtWidgets.QLineEdit(AddImage)
        self.lineEdit_add_imagename.setGeometry(QtCore.QRect(170, 100, 201, 31))
        self.lineEdit_add_imagename.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_imagename.setObjectName("lineEdit_add_imagename")
        self.pushButton_add_addimage = QtWidgets.QPushButton(AddImage)
        self.pushButton_add_addimage.setGeometry(QtCore.QRect(150, 480, 121, 41))
        self.pushButton_add_addimage.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_addimage.setObjectName("pushButton_add_addimage")
        self.lineEdit_add_imagedesc = QtWidgets.QLineEdit(AddImage)
        self.lineEdit_add_imagedesc.setGeometry(QtCore.QRect(170, 140, 201, 31))
        self.lineEdit_add_imagedesc.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_imagedesc.setObjectName("lineEdit_add_imagedesc")
        self.label_add_imagedesc = QtWidgets.QLabel(AddImage)
        self.label_add_imagedesc.setGeometry(QtCore.QRect(60, 140, 101, 31))
        self.label_add_imagedesc.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_imagedesc.setObjectName("label_add_imagedesc")
        self.label_add_disk_format = QtWidgets.QLabel(AddImage)
        self.label_add_disk_format.setGeometry(QtCore.QRect(60, 180, 101, 31))
        self.label_add_disk_format.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_disk_format.setObjectName("label_add_disk_format")
        self.label_add_min_disk = QtWidgets.QLabel(AddImage)
        self.label_add_min_disk.setGeometry(QtCore.QRect(60, 220, 101, 31))
        self.label_add_min_disk.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk.setObjectName("label_add_min_disk")
        self.spinBox_add_min_disk = QtWidgets.QSpinBox(AddImage)
        self.spinBox_add_min_disk.setGeometry(QtCore.QRect(170, 220, 171, 31))
        self.spinBox_add_min_disk.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_min_disk.setMaximum(99999)
        self.spinBox_add_min_disk.setObjectName("spinBox_add_min_disk")
        self.label_add_min_ram = QtWidgets.QLabel(AddImage)
        self.label_add_min_ram.setGeometry(QtCore.QRect(60, 260, 101, 31))
        self.label_add_min_ram.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_ram.setObjectName("label_add_min_ram")
        self.spinBox_add_min_ram = QtWidgets.QSpinBox(AddImage)
        self.spinBox_add_min_ram.setGeometry(QtCore.QRect(170, 260, 171, 31))
        self.spinBox_add_min_ram.setStyleSheet("QSpinBox {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"QSpinBox::up-button { subcontrol-origin: border; subcontrol-position: top right; width: 20px; height: 16px; image: url(\'resources/img/up-arrow.png\');}\n"
"QSpinBox::down-button { subcontrol-origin: border; subcontrol-position: bottom right; width: 20px; height: 16px; image: url(\'resources/img/down-arrow.png\');}")
        self.spinBox_add_min_ram.setMaximum(99999)
        self.spinBox_add_min_ram.setObjectName("spinBox_add_min_ram")
        self.radioButton_add_private = QtWidgets.QRadioButton(AddImage)
        self.radioButton_add_private.setGeometry(QtCore.QRect(170, 310, 91, 31))
        self.radioButton_add_private.setStyleSheet("QRadioButton {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-image: url(\'resources/img/selected.png\')\n"
"}")
        self.radioButton_add_private.setObjectName("radioButton_add_private")
        self.radioButton_add_shared = QtWidgets.QRadioButton(AddImage)
        self.radioButton_add_shared.setGeometry(QtCore.QRect(170, 340, 91, 31))
        self.radioButton_add_shared.setStyleSheet("QRadioButton {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-image: url(\'resources/img/selected.png\')\n"
"}")
        self.radioButton_add_shared.setObjectName("radioButton_add_shared")
        self.radioButton_add_public = QtWidgets.QRadioButton(AddImage)
        self.radioButton_add_public.setGeometry(QtCore.QRect(270, 340, 81, 31))
        self.radioButton_add_public.setStyleSheet("QRadioButton {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-image: url(\'resources/img/selected.png\')\n"
"}")
        self.radioButton_add_public.setObjectName("radioButton_add_public")
        self.label_add_visibility = QtWidgets.QLabel(AddImage)
        self.label_add_visibility.setGeometry(QtCore.QRect(60, 320, 101, 31))
        self.label_add_visibility.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_visibility.setObjectName("label_add_visibility")
        self.checkBox_add_add_ifprotected = QtWidgets.QCheckBox(AddImage)
        self.checkBox_add_add_ifprotected.setGeometry(QtCore.QRect(170, 380, 121, 31))
        self.checkBox_add_add_ifprotected.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_add_ifprotected.setObjectName("checkBox_add_add_ifprotected")
        self.label_add_protected = QtWidgets.QLabel(AddImage)
        self.label_add_protected.setGeometry(QtCore.QRect(60, 380, 101, 31))
        self.label_add_protected.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_protected.setObjectName("label_add_protected")
        self.pushButton_add_imagefile = QtWidgets.QPushButton(AddImage)
        self.pushButton_add_imagefile.setGeometry(QtCore.QRect(60, 420, 121, 31))
        self.pushButton_add_imagefile.setStyleSheet("QPushButton {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    background-color: #fff;\n"
"    color: #C32E24;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C32E24;\n"
"    color: #fff;\n"
"}")
        self.pushButton_add_imagefile.setObjectName("pushButton_add_imagefile")
        self.radioButton_add_social = QtWidgets.QRadioButton(AddImage)
        self.radioButton_add_social.setGeometry(QtCore.QRect(270, 310, 81, 31))
        self.radioButton_add_social.setStyleSheet("QRadioButton {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"     border-image: url(\'resources/img/selected.png\')\n"
"}")
        self.radioButton_add_social.setObjectName("radioButton_add_social")
        self.comboBox_add_disk_format = QtWidgets.QComboBox(AddImage)
        self.comboBox_add_disk_format.setGeometry(QtCore.QRect(170, 180, 201, 31))
        self.comboBox_add_disk_format.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    border-left: 1px solid transparent;;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #C32E24;\n"
"    border-radius: 6px;\n"
"    min-height: 60px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #C32E24;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::sub-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"                        ")
        self.comboBox_add_disk_format.setObjectName("comboBox_add_disk_format")
        self.lineEdit_add_imagefile = QtWidgets.QLineEdit(AddImage)
        self.lineEdit_add_imagefile.setGeometry(QtCore.QRect(190, 420, 181, 31))
        self.lineEdit_add_imagefile.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_imagefile.setObjectName("lineEdit_add_imagefile")
        self.label_add_min_disk_dw = QtWidgets.QLabel(AddImage)
        self.label_add_min_disk_dw.setGeometry(QtCore.QRect(350, 220, 31, 31))
        self.label_add_min_disk_dw.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_disk_dw.setObjectName("label_add_min_disk_dw")
        self.label_add_min_ram_dw = QtWidgets.QLabel(AddImage)
        self.label_add_min_ram_dw.setGeometry(QtCore.QRect(350, 260, 31, 31))
        self.label_add_min_ram_dw.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_min_ram_dw.setObjectName("label_add_min_ram_dw")

        self.retranslateUi(AddImage)
        QtCore.QMetaObject.connectSlotsByName(AddImage)

    def retranslateUi(self, AddImage):
        _translate = QtCore.QCoreApplication.translate
        AddImage.setWindowTitle(_translate("AddImage", "Dialog"))
        self.label_add_imagename.setText(_translate("AddImage", "镜像名称:"))
        self.label_addimagetitle.setText(_translate("AddImage", "<html><head/><body><p align=\"center\">创建镜像</p></body></html>"))
        self.pushButton_add_addimage.setText(_translate("AddImage", "创建"))
        self.label_add_imagedesc.setText(_translate("AddImage", "镜像描述:"))
        self.label_add_disk_format.setText(_translate("AddImage", "镜像格式:"))
        self.label_add_min_disk.setText(_translate("AddImage", "最小磁盘:"))
        self.label_add_min_ram.setText(_translate("AddImage", "最小内存:"))
        self.radioButton_add_private.setText(_translate("AddImage", "私有的"))
        self.radioButton_add_shared.setText(_translate("AddImage", "共享的"))
        self.radioButton_add_public.setText(_translate("AddImage", "公有"))
        self.label_add_visibility.setText(_translate("AddImage", "可见性:"))
        self.checkBox_add_add_ifprotected.setText(_translate("AddImage", "开启"))
        self.label_add_protected.setText(_translate("AddImage", "受保护:"))
        self.pushButton_add_imagefile.setText(_translate("AddImage", "选择镜像文件"))
        self.radioButton_add_social.setText(_translate("AddImage", "社区"))
        self.label_add_min_disk_dw.setText(_translate("AddImage", "GB"))
        self.label_add_min_ram_dw.setText(_translate("AddImage", "MB"))
