# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddSubnet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSubnet(object):
    def setupUi(self, AddSubnet):
        AddSubnet.setObjectName("AddSubnet")
        AddSubnet.resize(424, 550)
        AddSubnet.setMinimumSize(QtCore.QSize(424, 550))
        AddSubnet.setMaximumSize(QtCore.QSize(424, 550))
        AddSubnet.setStyleSheet("QDialog {background-color: white;}")
        self.label_add_subnetname = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetname.setGeometry(QtCore.QRect(60, 70, 101, 31))
        self.label_add_subnetname.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetname.setObjectName("label_add_subnetname")
        self.lineEdit_add_subnetname = QtWidgets.QLineEdit(AddSubnet)
        self.lineEdit_add_subnetname.setGeometry(QtCore.QRect(160, 70, 201, 31))
        self.lineEdit_add_subnetname.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_subnetname.setObjectName("lineEdit_add_subnetname")
        self.comboBox_add_subnetipversion = QtWidgets.QComboBox(AddSubnet)
        self.comboBox_add_subnetipversion.setGeometry(QtCore.QRect(160, 150, 201, 31))
        self.comboBox_add_subnetipversion.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"                        ")
        self.comboBox_add_subnetipversion.setObjectName("comboBox_add_subnetipversion")
        self.checkBox_add_subnetifgateway = QtWidgets.QCheckBox(AddSubnet)
        self.checkBox_add_subnetifgateway.setGeometry(QtCore.QRect(60, 230, 121, 31))
        self.checkBox_add_subnetifgateway.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_subnetifgateway.setObjectName("checkBox_add_subnetifgateway")
        self.label_addnetworktypetitle = QtWidgets.QLabel(AddSubnet)
        self.label_addnetworktypetitle.setGeometry(QtCore.QRect(130, 10, 161, 41))
        self.label_addnetworktypetitle.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 25px;\n"
"}")
        self.label_addnetworktypetitle.setObjectName("label_addnetworktypetitle")
        self.lineEdit_add_subnetcidr = QtWidgets.QLineEdit(AddSubnet)
        self.lineEdit_add_subnetcidr.setGeometry(QtCore.QRect(160, 110, 201, 31))
        self.lineEdit_add_subnetcidr.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_subnetcidr.setObjectName("lineEdit_add_subnetcidr")
        self.label_add_subnetcidr = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetcidr.setGeometry(QtCore.QRect(60, 110, 101, 31))
        self.label_add_subnetcidr.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetcidr.setObjectName("label_add_subnetcidr")
        self.label_add_subnetipversion = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetipversion.setGeometry(QtCore.QRect(60, 150, 101, 31))
        self.label_add_subnetipversion.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetipversion.setObjectName("label_add_subnetipversion")
        self.label_add_subnetgetwayip = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetgetwayip.setGeometry(QtCore.QRect(60, 190, 101, 31))
        self.label_add_subnetgetwayip.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetgetwayip.setObjectName("label_add_subnetgetwayip")
        self.lineEdit_add_subnetgatewayip = QtWidgets.QLineEdit(AddSubnet)
        self.lineEdit_add_subnetgatewayip.setGeometry(QtCore.QRect(160, 190, 201, 31))
        self.lineEdit_add_subnetgatewayip.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_subnetgatewayip.setText("")
        self.lineEdit_add_subnetgatewayip.setObjectName("lineEdit_add_subnetgatewayip")
        self.label_add_subnetipool = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetipool.setGeometry(QtCore.QRect(60, 270, 101, 31))
        self.label_add_subnetipool.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetipool.setObjectName("label_add_subnetipool")
        self.textEdit_add_subnetipool = QtWidgets.QTextEdit(AddSubnet)
        self.textEdit_add_subnetipool.setGeometry(QtCore.QRect(160, 270, 201, 51))
        self.textEdit_add_subnetipool.setStyleSheet("QTextEdit {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}")
        self.textEdit_add_subnetipool.setObjectName("textEdit_add_subnetipool")
        self.textEdit_add_subnetdns = QtWidgets.QTextEdit(AddSubnet)
        self.textEdit_add_subnetdns.setGeometry(QtCore.QRect(160, 330, 201, 51))
        self.textEdit_add_subnetdns.setStyleSheet("QTextEdit {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}")
        self.textEdit_add_subnetdns.setObjectName("textEdit_add_subnetdns")
        self.label_add_subnetdns = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetdns.setGeometry(QtCore.QRect(60, 330, 101, 31))
        self.label_add_subnetdns.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetdns.setObjectName("label_add_subnetdns")
        self.label_add_subnetroute = QtWidgets.QLabel(AddSubnet)
        self.label_add_subnetroute.setGeometry(QtCore.QRect(60, 390, 101, 31))
        self.label_add_subnetroute.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_subnetroute.setObjectName("label_add_subnetroute")
        self.textEdit_add_subnetroute = QtWidgets.QTextEdit(AddSubnet)
        self.textEdit_add_subnetroute.setGeometry(QtCore.QRect(160, 390, 201, 51))
        self.textEdit_add_subnetroute.setStyleSheet("QTextEdit {font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;}")
        self.textEdit_add_subnetroute.setObjectName("textEdit_add_subnetroute")
        self.pushButton_add_addsubnet = QtWidgets.QPushButton(AddSubnet)
        self.pushButton_add_addsubnet.setGeometry(QtCore.QRect(150, 470, 121, 41))
        self.pushButton_add_addsubnet.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_addsubnet.setObjectName("pushButton_add_addsubnet")
        self.checkBox_add_subnetifdhcp = QtWidgets.QCheckBox(AddSubnet)
        self.checkBox_add_subnetifdhcp.setGeometry(QtCore.QRect(200, 230, 131, 31))
        self.checkBox_add_subnetifdhcp.setStyleSheet("QCheckBox {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #ffffff;\n"
"    color: #C32E24;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"     width:18px;\n"
"     height: 18px;\n"
"     background-color: #ffffff;\n"
"     border: 1px solid #ddd;\n"
"     border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"     border-image: url(\'resources/img/checked.png\');\n"
"    border: 1px solid #ddd;\n"
"}")
        self.checkBox_add_subnetifdhcp.setObjectName("checkBox_add_subnetifdhcp")

        self.retranslateUi(AddSubnet)
        QtCore.QMetaObject.connectSlotsByName(AddSubnet)

    def retranslateUi(self, AddSubnet):
        _translate = QtCore.QCoreApplication.translate
        AddSubnet.setWindowTitle(_translate("AddSubnet", "Dialog"))
        self.label_add_subnetname.setText(_translate("AddSubnet", "子网名称:"))
        self.checkBox_add_subnetifgateway.setText(_translate("AddSubnet", "禁用网关"))
        self.label_addnetworktypetitle.setText(_translate("AddSubnet", "<html><head/><body><p align=\"center\">创建子网</p></body></html>"))
        self.label_add_subnetcidr.setText(_translate("AddSubnet", "网络地址:"))
        self.label_add_subnetipversion.setText(_translate("AddSubnet", "IP版本:"))
        self.label_add_subnetgetwayip.setText(_translate("AddSubnet", "网关IP:"))
        self.label_add_subnetipool.setText(_translate("AddSubnet", "分配IP池:"))
        self.label_add_subnetdns.setText(_translate("AddSubnet", "DNS:"))
        self.label_add_subnetroute.setText(_translate("AddSubnet", "主机路由:"))
        self.pushButton_add_addsubnet.setText(_translate("AddSubnet", "创建"))
        self.checkBox_add_subnetifdhcp.setText(_translate("AddSubnet", "激活DHCP"))
