# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddServer(object):
    def setupUi(self, AddServer):
        AddServer.setObjectName("AddServer")
        AddServer.resize(441, 378)
        AddServer.setStyleSheet("QDialog {background-color: white;}\n"
"")
        self.label_addservertitle = QtWidgets.QLabel(AddServer)
        self.label_addservertitle.setGeometry(QtCore.QRect(140, 10, 161, 41))
        self.label_addservertitle.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 25px;\n"
"}")
        self.label_addservertitle.setObjectName("label_addservertitle")
        self.label_add_servername = QtWidgets.QLabel(AddServer)
        self.label_add_servername.setGeometry(QtCore.QRect(50, 80, 101, 31))
        self.label_add_servername.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_servername.setObjectName("label_add_servername")
        self.lineEdit_add_servername = QtWidgets.QLineEdit(AddServer)
        self.lineEdit_add_servername.setGeometry(QtCore.QRect(170, 80, 201, 31))
        self.lineEdit_add_servername.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_add_servername.setObjectName("lineEdit_add_servername")
        self.label_add_serverzone = QtWidgets.QLabel(AddServer)
        self.label_add_serverzone.setGeometry(QtCore.QRect(50, 120, 101, 31))
        self.label_add_serverzone.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_serverzone.setObjectName("label_add_serverzone")
        self.comboBox_add_serverzone = QtWidgets.QComboBox(AddServer)
        self.comboBox_add_serverzone.setGeometry(QtCore.QRect(170, 120, 201, 31))
        self.comboBox_add_serverzone.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    border-left: 1px solid transparent;;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #C32E24;\n"
"    border-radius: 6px;\n"
"    min-height: 60px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #C32E24;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::sub-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"                        ")
        self.comboBox_add_serverzone.setObjectName("comboBox_add_serverzone")
        self.pushButton_add_addserver = QtWidgets.QPushButton(AddServer)
        self.pushButton_add_addserver.setGeometry(QtCore.QRect(150, 300, 121, 41))
        self.pushButton_add_addserver.setStyleSheet("QPushButton{\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    background-color: #C32E24;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: #C32E24;\n"
"}")
        self.pushButton_add_addserver.setObjectName("pushButton_add_addserver")
        self.label_add_serverimg = QtWidgets.QLabel(AddServer)
        self.label_add_serverimg.setGeometry(QtCore.QRect(50, 160, 101, 31))
        self.label_add_serverimg.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_serverimg.setObjectName("label_add_serverimg")
        self.comboBox_add_serverimage = QtWidgets.QComboBox(AddServer)
        self.comboBox_add_serverimage.setGeometry(QtCore.QRect(170, 160, 201, 31))
        self.comboBox_add_serverimage.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    border-left: 1px solid transparent;;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #C32E24;\n"
"    border-radius: 6px;\n"
"    min-height: 60px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #C32E24;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::sub-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"                        ")
        self.comboBox_add_serverimage.setObjectName("comboBox_add_serverimage")
        self.label_add_serverflavor = QtWidgets.QLabel(AddServer)
        self.label_add_serverflavor.setGeometry(QtCore.QRect(50, 200, 111, 31))
        self.label_add_serverflavor.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_serverflavor.setObjectName("label_add_serverflavor")
        self.comboBox_add_serverflavor = QtWidgets.QComboBox(AddServer)
        self.comboBox_add_serverflavor.setGeometry(QtCore.QRect(170, 200, 201, 31))
        self.comboBox_add_serverflavor.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    border-left: 1px solid transparent;;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #C32E24;\n"
"    border-radius: 6px;\n"
"    min-height: 60px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #C32E24;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::sub-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"                        ")
        self.comboBox_add_serverflavor.setObjectName("comboBox_add_serverflavor")
        self.label_add_servernetwork = QtWidgets.QLabel(AddServer)
        self.label_add_servernetwork.setGeometry(QtCore.QRect(50, 240, 111, 31))
        self.label_add_servernetwork.setStyleSheet("QLabel {\n"
"    color: #C32E24;\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    font-size: 20px;\n"
"}")
        self.label_add_servernetwork.setObjectName("label_add_servernetwork")
        self.comboBox_add_servernetwork = QtWidgets.QComboBox(AddServer)
        self.comboBox_add_servernetwork.setGeometry(QtCore.QRect(170, 240, 201, 31))
        self.comboBox_add_servernetwork.setStyleSheet("QComboBox {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;    \n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\'resources/img/down-arrow.png\'); \n"
"    width: 15px;\n"
"    height: 15px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border:0;           \n"
"    min-width: 40px; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    border-left: 1px solid transparent;;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #C32E24;\n"
"    border-radius: 6px;\n"
"    min-height: 60px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #C32E24;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::sub-page {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: url(none) center no-repeat;\n"
"}\n"
"                        ")
        self.comboBox_add_servernetwork.setObjectName("comboBox_add_servernetwork")

        self.retranslateUi(AddServer)
        QtCore.QMetaObject.connectSlotsByName(AddServer)

    def retranslateUi(self, AddServer):
        _translate = QtCore.QCoreApplication.translate
        AddServer.setWindowTitle(_translate("AddServer", "Dialog"))
        self.label_addservertitle.setText(_translate("AddServer", "<html><head/><body><p align=\"center\">创建云主机</p></body></html>"))
        self.label_add_servername.setText(_translate("AddServer", "实例名称:"))
        self.label_add_serverzone.setText(_translate("AddServer", "可用域:"))
        self.pushButton_add_addserver.setText(_translate("AddServer", "创建"))
        self.label_add_serverimg.setText(_translate("AddServer", "镜像:"))
        self.label_add_serverflavor.setText(_translate("AddServer", "云主机类型:"))
        self.label_add_servernetwork.setText(_translate("AddServer", "网络选择:"))
