# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1120, 740)
        Login.setStyleSheet("QWidget {background-color:white;}")
        self.frame_login = QtWidgets.QFrame(Login)
        self.frame_login.setGeometry(QtCore.QRect(531, 21, 591, 691))
        self.frame_login.setStyleSheet("QWidget {background-color:white;}")
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.label_ins = QtWidgets.QLabel(self.frame_login)
        self.label_ins.setGeometry(QtCore.QRect(140, 150, 321, 41))
        self.label_ins.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            font-size: 30px;\n"
"                            }\n"
"                        ")
        self.label_ins.setObjectName("label_ins")
        self.label_password = QtWidgets.QLabel(self.frame_login)
        self.label_password.setGeometry(QtCore.QRect(130, 370, 81, 41))
        self.label_password.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            font-size: 25px;\n"
"                            }\n"
"                        ")
        self.label_password.setObjectName("label_password")
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame_login)
        self.lineEdit_username.setGeometry(QtCore.QRect(220, 310, 251, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_username.setFrame(True)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_title = QtWidgets.QLabel(self.frame_login)
        self.label_title.setGeometry(QtCore.QRect(90, 70, 441, 71))
        self.label_title.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"font-size: 50px;\n"
"text-align: center;\n"
"}\n"
"                        ")
        self.label_title.setObjectName("label_title")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_login)
        self.lineEdit_password.setGeometry(QtCore.QRect(220, 370, 251, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            border: 1px solid #ddd;\n"
"                            box-shadow: none;\n"
"                            color: #333;\n"
"                            font-size: 15px;\n"
"                            border-radius: 10px;\n"
"                            }\n"
"                        ")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_exit.setGeometry(QtCore.QRect(310, 550, 161, 51))
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"                            border-radius: 10px;\n"
"                            border: #69a9ff 1px solid;\n"
"                            font: 9qt \'微软雅黑\';\n"
"                            background-color: #5c5c5c;\n"
"                            font-size: 20px;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #cccccc;\n"
"                            }\n"
"                        ")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_ip = QtWidgets.QLabel(self.frame_login)
        self.label_ip.setGeometry(QtCore.QRect(130, 250, 81, 41))
        self.label_ip.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            font-size: 25px;\n"
"                            }\n"
"                        ")
        self.label_ip.setObjectName("label_ip")
        self.label_demo = QtWidgets.QLabel(self.frame_login)
        self.label_demo.setGeometry(QtCore.QRect(130, 430, 81, 41))
        self.label_demo.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            font-size: 25px;\n"
"                            }\n"
"                        ")
        self.label_demo.setObjectName("label_demo")
        self.pushButton_link = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_link.setGeometry(QtCore.QRect(130, 550, 161, 51))
        self.pushButton_link.setStyleSheet("QPushButton {\n"
"                            border-radius: 10px;\n"
"                            border: #69a9ff 1px solid;\n"
"                            font: 9qt \'微软雅黑\';\n"
"                            background-color: #C32E24;\n"
"                            font-size: 20px;\n"
"                            color: white;\n"
"                            }\n"
"\n"
"                            QPushButton:hover {\n"
"                            background-color: #fc624e;\n"
"                            }\n"
"                        ")
        self.pushButton_link.setObjectName("pushButton_link")
        self.label_username = QtWidgets.QLabel(self.frame_login)
        self.label_username.setGeometry(QtCore.QRect(130, 310, 81, 41))
        self.label_username.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            font-size: 25px;\n"
"                            }\n"
"                        ")
        self.label_username.setObjectName("label_username")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.frame_login)
        self.lineEdit_ip.setGeometry(QtCore.QRect(220, 250, 251, 41))
        self.lineEdit_ip.setStyleSheet("QLineEdit {\n"
"                            border: 1px solid #ddd;\n"
"                            box-shadow: none;\n"
"                            color: #333;\n"
"                            font-size: 15px;\n"
"                            border-radius: 10px;\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            }\n"
"                        ")
        self.lineEdit_ip.setFrame(True)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_project = QtWidgets.QLabel(self.frame_login)
        self.label_project.setGeometry(QtCore.QRect(130, 490, 81, 41))
        self.label_project.setStyleSheet("QLabel {\n"
"font: 57 9pt \"HarmonyOS Sans SC\";\n"
"                            font-size: 25px;\n"
"                            }\n"
"                        ")
        self.label_project.setObjectName("label_project")
        self.lineEdit_userdomain = QtWidgets.QLineEdit(self.frame_login)
        self.lineEdit_userdomain.setGeometry(QtCore.QRect(220, 430, 251, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_userdomain.setFont(font)
        self.lineEdit_userdomain.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_userdomain.setFrame(True)
        self.lineEdit_userdomain.setObjectName("lineEdit_userdomain")
        self.lineEdit_userproject = QtWidgets.QLineEdit(self.frame_login)
        self.lineEdit_userproject.setGeometry(QtCore.QRect(220, 490, 251, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_userproject.setFont(font)
        self.lineEdit_userproject.setStyleSheet("QLineEdit {\n"
"    font: 57 9pt \"HarmonyOS Sans SC\";\n"
"    border: 1px solid #ddd;\n"
"    box-shadow: none;\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"}\n"
"                        ")
        self.lineEdit_userproject.setFrame(True)
        self.lineEdit_userproject.setObjectName("lineEdit_userproject")
        self.frame_logo = QtWidgets.QFrame(Login)
        self.frame_logo.setGeometry(QtCore.QRect(0, 20, 531, 691))
        self.frame_logo.setStyleSheet("QWidget {background-color:white;}")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.widget = QtWidgets.QWidget(self.frame_logo)
        self.widget.setGeometry(QtCore.QRect(20, 240, 461, 171))
        self.widget.setStyleSheet("QWidget {\n"
"    display: block;\n"
"    margin: 0 auto;\n"
"    width: 100%;\n"
"    height: 100%;\n"
"    background: url(resources/img/logo.png) no-repeat center;\n"
"    background-size: contain;\n"
"    cursor: pointer;\n"
"    transition: all 0.3s ease;\n"
"}\n"
"                        ")
        self.widget.setObjectName("widget")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label_ins.setText(_translate("Login", "连接到你的OpenStack"))
        self.label_password.setText(_translate("Login", "密 码:"))
        self.label_title.setText(_translate("Login", "OpenStack Client"))
        self.pushButton_exit.setText(_translate("Login", "退出"))
        self.label_ip.setText(_translate("Login", "IP地址:"))
        self.label_demo.setText(_translate("Login", "域:"))
        self.pushButton_link.setText(_translate("Login", "连接"))
        self.label_username.setText(_translate("Login", "用户名:"))
        self.label_project.setText(_translate("Login", "项目:"))
